# Generated by Django 2.2.7 on 2019-11-25 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('titleEng', models.CharField(default='', max_length=100)),
                ('director', models.CharField(default='', max_length=50)),
                ('actors', models.CharField(default='', max_length=100)),
                ('nation', models.CharField(default='', max_length=50)),
                ('plot', models.TextField()),
                ('runtime', models.CharField(default='', max_length=50)),
                ('ratingGrade', models.CharField(default='', max_length=50)),
                ('releaseDt', models.DateField()),
                ('descriptions', models.CharField(default='', max_length=100)),
                ('poster', models.CharField(default='', max_length=100)),
                ('stills', models.TextField()),
                ('awards', models.TextField()),
                ('genre1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movie_main_genre', to='movies.Genre')),
                ('genre2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movie_sub_genre', to='movies.Genre')),
                ('keyword1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movie_main_keyword', to='movies.Keyword')),
                ('keyword2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movie_sub_keyword1', to='movies.Keyword')),
                ('keyword3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movie_sub_keyword2', to='movies.Keyword')),
            ],
        ),
        migrations.CreateModel(
            name='User_Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Keyword')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField()),
                ('comment', models.CharField(max_length=100)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Movie_Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Keyword')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Movie')),
            ],
        ),
    ]
