# Generated by Django 2.2.7 on 2019-11-25 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='releaseDt',
            field=models.CharField(default='', max_length=50),
        ),
    ]
