# Generated by Django 2.2.7 on 2019-11-26 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='keyword1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rating_main_keword', to='movies.Keyword'),
        ),
        migrations.AddField(
            model_name='rating',
            name='keyword2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rating_sub_keyword', to='movies.Keyword'),
        ),
    ]
